---
commit_timeout: 120
confirm_time: 10
config_assemble: "{{ user_data_path }}/config/{{ inventory_hostname }}"
config_assemble_build: "{{ config_assemble }}/build"
connection_settings:
  server: "{{ ansible_host }}"
  server_port: "{{ 443 }}"
  timeout: "{{ commit_timeout }}"
  validate_certs: false
file_name: "backup_{{ inventory_hostname }}_{{ ansible_date_time.date }}.ucs"
local_folder_location: "/var/f5_backup"
ftp_remote_path: "/backup/F5_WAF"
ftp_port: 21