---
- name: BIG-IP SETUP
  hosts: "{{ services }}"
  roles:
    - build_config
    - telegram
  connection: local
  gather_facts: true

  vars:
      config_file: "{{ config_assemble }}/all.conf"

  tasks:
    - name: Setup provider
      ansible.builtin.set_fact:
        provider: "{{ connection_settings }}"

    - name: Download a new UCS
      f5networks.f5_modules.bigip_ucs_fetch:
        src: "{{file_name}}"
        dest: "{{local_folder_location}}/{{file_name}}"
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Ensure local backup folder exists
      ansible.builtin.file:
        path: "{{ local_folder_location }}"
        state: directory

    - name: Upload backup file to FTP server using curl
      ansible.builtin.shell: 
        cmd: curl -T "{{ local_folder_location }}/{{ file_name }}" ftp://{{ ftp_server }}/{{ ftp_remote_path }}/ --user "{{ ftp_username }}:{{ ftp_password }}"
      args:
        warn: false