---
- name: Send notify to Telegram
  community.general.telegram:
    token: '6482398803:AAGxJOsriVhWRvsM-VMd4ZehsvfS0ZCUXQE'
    api_args:
      chat_id: -1002094147640
      parse_mode: "MarkdownV2"
      text: "[{{ services }}] Backup complete"
      disable_web_page_preview: True
      disable_notification: True
