---
- name: Send notify to Telegram
  community.general.telegram:
    token: '{{ lookup('credential', 'token_tele') }}'
    api_args:
      chat_id: -1002094147640
      parse_mode: "MarkdownV2"
      text: "Backup complete node {{ ansible_host| regex_escape() }} on {{ ansible_date_time.iso8601 | regex_escape()}}"
      disable_web_page_preview: True
      disable_notification: True